# Configuration for the ESP Overlay MVP

capture:
  # Type of capture source: 'webcam', 'elgato', 'screen'
  type: 'elgato' # Default to webcam for ease of testing

  # --- Webcam/Elgato Settings ---
  # Device index (usually 0, 1, ...)
  # For Elgato Neo, find the correct index it appears as.
  device_index: 1
  # Desired resolution (width, height). Set to null to use default.
  resolution: [1920, 1080] # Target 1080p
  # Desired FPS. Set to null to use default.
  fps: 60 # Target 60 FPS

  # --- Screen Capture Settings ---
  # Monitor number (1 for primary, 2 for secondary, etc.)
  monitor: 1
  # Bounding box for capture region [left, top, width, height]. Set to null for full monitor.
  # Example: capture only top-left 800x600 region: [0, 0, 800, 600]
  region: null

ai:
  # Path to the ONNX model file
  model_path: 'models/yolov5n.onnx' # User needs to provide this model
  # Confidence threshold for detections (0.0 to 1.0)
  confidence_threshold: 0.4
  # Non-Maximum Suppression (NMS) threshold (0.0 to 1.0)
  nms_threshold: 0.5
  # Class IDs to detect (e.g., [0] for 'person' in COCO)
  # Check your model's class definition. Set to null to detect all classes.
  classes_to_detect: [0] # Example: Detect only persons

output:
  # Show the FPS on the output window
  show_fps: true
  # Window title
  window_title: 'ESP Overlay MVP'

# --- Advanced / Performance ---
# Max size of the frame queue between capture and processing
# Smaller values reduce latency but might drop more frames if AI is slow.
# Larger values buffer more, increasing latency but smoothing temporary slowdowns.
# 1 or 2 is usually good for low latency.
frame_queue_size: 2

# Use GPU for ONNX Runtime? Requires onnxruntime-gpu package and compatible hardware/drivers.
# Set to false to use CPU.
use_gpu: false 